/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package steganografi;

import java.awt.FlowLayout;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.FileOutputStream;
import java.nio.ByteBuffer;
import java.nio.file.Files;
import java.nio.file.Paths;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author Fahziar
 */
public class MainWindow extends javax.swing.JApplet {

    /**
     * Initializes the applet MainWindow
     */
    
    BufferedImage image1;
    BufferedImage image2;
    BufferedImage biCopy;
    BufferedImage biCopy2;
    
    NineDiffStego nineDiffStego;
    Stegano stego;
    FourDiffStego fourDiffStego;
    
    boolean grayscale;
    
    public MainWindow()
    {
        nineDiffStego = new NineDiffStego();
        stego = new Stegano();
        fourDiffStego = new FourDiffStego();
        
        grayscale = false;
    }
    
    @Override
    public void init() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the applet */
        try {
            java.awt.EventQueue.invokeAndWait(new Runnable() {
                public void run() {
                    initComponents();
                }
            });
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }

    /**
     * This method is called from within the init() method to initialize the
     * form. WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        btnLoadGambar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        cmbAlgoritma = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        txtKapasitas = new javax.swing.JTextField();
        btnExtractData = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtPassword = new javax.swing.JTextField();
        btnPutData = new javax.swing.JButton();
        btnPSNR = new javax.swing.JButton();
        btnViewOriginal = new javax.swing.JButton();
        btnViewStegano = new javax.swing.JButton();
        checkGrayscale = new javax.swing.JCheckBox();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        btnLoadGambar.setText("Load Picture");
        btnLoadGambar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLoadGambarMouseClicked(evt);
            }
        });
        btnLoadGambar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoadGambarActionPerformed(evt);
            }
        });

        jLabel1.setText("Algorithm:");

        cmbAlgoritma.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "LSB", "5 Pixel Diff", "9 Pixel Diff" }));

        jLabel2.setText("Kapasitas");

        txtKapasitas.setEditable(false);

        btnExtractData.setText("Extract Data");
        btnExtractData.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnExtractDataMouseClicked(evt);
            }
        });
        btnExtractData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExtractDataActionPerformed(evt);
            }
        });

        jLabel3.setText("Password: ");

        btnPutData.setText("Put Data");
        btnPutData.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPutDataMouseClicked(evt);
            }
        });

        btnPSNR.setText("PSNR");
        btnPSNR.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPSNRMouseClicked(evt);
            }
        });

        btnViewOriginal.setText("View Original Picture");
        btnViewOriginal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnViewOriginalMouseClicked(evt);
            }
        });

        btnViewStegano.setText("View Stegano Picture");
        btnViewStegano.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnViewSteganoMouseClicked(evt);
            }
        });

        checkGrayscale.setText("Grayscale");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnPSNR, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtPassword))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnLoadGambar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnPutData, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtKapasitas, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE)
                            .addComponent(btnExtractData, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmbAlgoritma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(checkGrayscale))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnViewOriginal)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnViewStegano)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(cmbAlgoritma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtKapasitas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnLoadGambar))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnExtractData)
                    .addComponent(btnPutData))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(checkGrayscale)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addComponent(btnPSNR)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnViewStegano)
                    .addComponent(btnViewOriginal))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoadGambarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoadGambarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLoadGambarActionPerformed

    private void btnExtractDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExtractDataActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnExtractDataActionPerformed

    private void btnLoadGambarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLoadGambarMouseClicked
        // TODO add your handling code here:
        JFileChooser fc = new JFileChooser();
        
        nineDiffStego = new NineDiffStego();
        stego = new Stegano();
        
        fc.setDialogTitle("Open Image");
        fc.showOpenDialog(this);
        try{
            image1 = ImageIO.read(fc.getSelectedFile().getAbsoluteFile());
            image2 = ImageIO.read(fc.getSelectedFile().getAbsoluteFile());
        } catch (Exception e){
            JOptionPane.showMessageDialog(this, "Gagal membuka file: " + e.getMessage());
        }
        
        switch (cmbAlgoritma.getSelectedIndex())
        {
            case 0:
                stego.setImage(image1);
                if (image1.getType() == BufferedImage.TYPE_BYTE_GRAY)
                {
                    txtKapasitas.setText(Integer.toString(stego.getCapacityGray()- 8));
                    biCopy = new BufferedImage(image1.getWidth(), image1.getHeight(), BufferedImage.TYPE_INT_RGB);
                    for (int x = 0; x < image1.getWidth(); x++) {
                        for (int y = 0; y < image1.getHeight(); y++) {
                            biCopy.setRGB(x, y, image1.getRGB(x, y));
                        }
                    }
                    
                    biCopy2 = new BufferedImage(image1.getWidth(), image1.getHeight(), BufferedImage.TYPE_INT_RGB);
                    for (int x = 0; x < image1.getWidth(); x++) {
                        for (int y = 0; y < image1.getHeight(); y++) {
                            biCopy.setRGB(x, y, image1.getRGB(x, y));
                        }
                    }
                    
                    stego.setImage(biCopy);
                } else {
                    txtKapasitas.setText(Integer.toString(stego.getCapacityTrue() - 8));
                }
                
                break;
            case 1:
                break;
            case 2:
                nineDiffStego.setImage(image1);
                nineDiffStego.setImage2(image2);
                if (image1.getType() == BufferedImage.TYPE_BYTE_GRAY)
                {
                    txtKapasitas.setText(Integer.toString(nineDiffStego.getCapacityGrayscale()));
                    
                    biCopy = new BufferedImage(image1.getWidth(), image1.getHeight(), BufferedImage.TYPE_INT_RGB);
                    for (int x = 0; x < image1.getWidth(); x++) {
                        for (int y = 0; y < image1.getHeight(); y++) {
                            biCopy.setRGB(x, y, image1.getRGB(x, y));
                        }
                    }
                    
                    biCopy2 = new BufferedImage(image1.getWidth(), image1.getHeight(), BufferedImage.TYPE_INT_RGB);
                    for (int x = 0; x < image1.getWidth(); x++) {
                        for (int y = 0; y < image1.getHeight(); y++) {
                            biCopy.setRGB(x, y, image1.getRGB(x, y));
                        }
                    }
                    
                    nineDiffStego.setImage(biCopy);
                    nineDiffStego.setImage2(biCopy2);
                } else {
                    txtKapasitas.setText(Integer.toString(nineDiffStego.getCapacity()));
                }
                break;
        }
        
    }//GEN-LAST:event_btnLoadGambarMouseClicked

    private void btnPutDataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPutDataMouseClicked
        // TODO add your handling code here:
        JFileChooser fc = new JFileChooser();
        
        fc.setDialogTitle("Open File to Hide");
        fc.showOpenDialog(this);
        
        try
        {
            byte[] inputData = Files.readAllBytes(Paths.get(fc.getSelectedFile().getAbsolutePath()));
            String[] splited = fc.getSelectedFile().getName().split("\\.");
            
            //Encrypt
            byte[] encrypted = VigenereCipher.vigenereExtendedEncryptBytes(txtPassword.getText(), inputData);
            ByteBuffer bf = ByteBuffer.allocate(12 + encrypted.length );
            
            int i;
            switch (cmbAlgoritma.getSelectedIndex())
            {
                case 0:
                    i=0;
                    while((i<4) && (i < splited[splited.length - 1].length()))
                    {
                        bf.putChar(splited[splited.length - 1].charAt(i));
                        i++;
                    }
                    
                    for(;i<4;i++)
                    {
                        bf.putChar(' ');
                    }
                    
                    bf.putInt(encrypted.length);
                    bf.put(encrypted);
                    
                    //Cek kapasitas
                        
                    
                    if(image1.getType() == BufferedImage.TYPE_BYTE_GRAY)
                    {
                        if (bf.capacity() > stego.getCapacityGray())
                        {
                            JOptionPane.showMessageDialog(this, "Kapasitas tidak mencukupi");
                            throw new RuntimeException("Kapasitas tidak mencukupi");
                        }
                        stego.setImage(biCopy);
                        stego.insertDataGray(txtPassword.getText(), bf.array());
                    } else {
                        if (bf.capacity() > stego.getCapacityTrue())
                        {
                            JOptionPane.showMessageDialog(this, "Kapasitas tidak mencukupi");
                            throw new RuntimeException("Kapasitas tidak mencukupi");
                        }
                        stego.insertData(txtPassword.getText(), bf.array());
                    }
                    fc.setDialogTitle("Save Stego Image");
                    fc.showSaveDialog(this);
                    ImageIO.write(stego.getImage(), "bmp", fc.getSelectedFile().getAbsoluteFile());
                    image1 = stego.getImage();
                    break;
                case 1:
                    bf = ByteBuffer.allocate(8 + encrypted.length);
                    i=0;
                    while((i<4) && (i < splited[splited.length - 1].length()))
                    {
                        bf.putChar(splited[splited.length - 1].charAt(i));
                        i++;
                    }
                    
                    for(;i<4;i++)
                    {
                        bf.putChar(' ');
                    }
                    bf.put(encrypted);
                    
                    bf.flip();
                    String msg="";
                    for (i =0; i<bf.capacity(); i++){
                        msg += Integer.toBinaryString(bf.get()); //ubah pesan jadi String 10001011110
                    }
                    //EOF
                    msg += Integer.toBinaryString(65);
                    msg += Integer.toBinaryString(70);
                    msg += Integer.toBinaryString(73);
                    msg += Integer.toBinaryString(75);
                    String msgsize  = Integer.toBinaryString(bf.capacity());
                    fourDiffStego.setMessage(msg);
                    System.out.println("msg len : " + msg.length() + " bit");
                    System.out.println(msg);
                    
                    fourDiffStego.setCoverImage(image1);
                    fourDiffStego.setStegoImage(image1);
                    
                    int size = fourDiffStego.getCapacity();
                    
                    if (bf.capacity() > size/8){
                        JOptionPane.showMessageDialog(this, "Kapasitas tidak mencukupi");
                        throw new RuntimeException("Kapasitas tidak mencukupi");
                    }
                    else {
                      fourDiffStego.hideMessage();
                      fc.setDialogTitle("Save Output File");
                      fc.showSaveDialog(this);
                      ImageIO.write(fourDiffStego.getStegoImage(), "bmp", fc.getSelectedFile());
                      image1 = fourDiffStego.getStegoImage();
                    }
                    break;
                case 2:
                    i=0;
                    while((i<4) && (i < splited[splited.length - 1].length()))
                    {
                        bf.putChar(splited[splited.length - 1].charAt(i));
                        i++;
                    }
                    
                    for(;i<4;i++)
                    {
                        bf.putChar(' ');
                    }
                    
                    bf.putInt(encrypted.length);
                    bf.put(encrypted);
                    
                    if(image1.getType() == BufferedImage.TYPE_BYTE_GRAY)
                    {
                        if (bf.capacity() > nineDiffStego.getCapacityGrayscale())
                        {
                            JOptionPane.showMessageDialog(this, "Kapasitas tidak mencukupi");
                            throw new RuntimeException("Kapasitas tidak mencukupi");
                        }
                        nineDiffStego.setImage(biCopy);
                        nineDiffStego.setImage(biCopy2);
                        nineDiffStego.stegoGrayscale("hello", bf.array());
                    } else {
                        if (bf.capacity() > nineDiffStego.getCapacity())
                        {
                            JOptionPane.showMessageDialog(this, "Kapasitas tidak mencukupi");
                            throw new RuntimeException("Kapasitas tidak mencukupi");
                        }
                        nineDiffStego.stego("hello", bf.array());
                    }
                    fc.setDialogTitle("Save Stego Image");
                    fc.showSaveDialog(this);
                    ImageIO.write(nineDiffStego.getImage(), "bmp", fc.getSelectedFile().getAbsoluteFile());
                    image1 = nineDiffStego.getImage();
                    break;
            }
        } catch (Exception e)
        {
            
        }
    }//GEN-LAST:event_btnPutDataMouseClicked

    private void btnExtractDataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExtractDataMouseClicked
        // TODO add your handling code here:
        boolean success = true;
        char a, b, c, d;
        a = b = c = d = ' ';
        
        byte[] out = new byte[1];
        byte[] metadata;
        ByteBuffer bf, bf2;
        int size, i;
        byte[] notStegoed;
        
        switch (cmbAlgoritma.getSelectedIndex())
        {
            case 0:
                stego.setImage(image1);
                stego.setImage2(image1);
                
                if (checkGrayscale.isSelected())
                {
                    stego.setImage(image1);
                    stego.setImage2(image1);
                    metadata = stego.extractDataGray(txtPassword.getText(), 96);
                } else {
                    metadata = stego.extractData(txtPassword.getText(), 96);
                }
            
                bf = ByteBuffer.allocate(13);
                bf.put(metadata);
                bf.flip();
                
                //bf.flip();
                a = bf.getChar();
                b = bf.getChar();
                c = bf.getChar();
                d = bf.getChar();

                size = bf.getInt();
                
                if (checkGrayscale.isSelected())
                {
                    notStegoed = stego.extractDataGray(txtPassword.getText(), (size + 12) * 8);
                } else {
                    notStegoed = stego.extractData(txtPassword.getText(), (size + 12) * 8);
                }
                
                bf.clear();
                bf2 = ByteBuffer.allocate(notStegoed.length);
                bf2.put(notStegoed);
                bf2.flip();
                

                out = new byte[size];

                for(i=0; i<4;i++)
                {
                    bf2.getChar();
                }
                bf2.getInt();
                bf2.get(out);
                
                break;
            case 1:
                String msg="100110011011111110010110";
                fourDiffStego.setCoverImage(image1);
                fourDiffStego.setStegoImage(image1);
                msg = fourDiffStego.extractMessage();
                System.out.println(msg);

                String msgfinal;   
                msgfinal = fourDiffStego.bitToText(msg);
                
                a = msgfinal.charAt(0);
                b = msgfinal.charAt(1);
                c = msgfinal.charAt(2);
                d = msgfinal.charAt(3);
                
                out = msgfinal.substring(4).getBytes();
                                
                break;
            case 2:
                nineDiffStego.setImage(image1);
                nineDiffStego.setImage2(image2);
                if (checkGrayscale.isSelected())
                {
                    metadata = nineDiffStego.unStegoGrayscale("hello", 96);
                } else {
                    metadata = nineDiffStego.unStego("hello", 96);
                }
            
                bf = ByteBuffer.allocate(13);
                bf.put(metadata);
                bf.flip();
                                
                //bf.flip();
                a = bf.getChar();
                b = bf.getChar();
                c = bf.getChar();
                d = bf.getChar();

                size = bf.getInt();
                if (checkGrayscale.isSelected())
                {
                    notStegoed = nineDiffStego.unStegoGrayscale("hello", (size + 12) * 8);
                } else {
                    notStegoed = nineDiffStego.unStego("hello", (size + 12) * 8);
                }
                
                bf.clear();
                bf2 = ByteBuffer.allocate(notStegoed.length);
                bf2.put(notStegoed);
                bf2.flip();
                
                out = new byte[size];

                for(i=0; i<4;i++)
                {
                    bf2.getChar();
                }
                bf2.getInt();
                bf2.get(out);
                
                break;
        } 
        if (success)
        {
            try {
                
                JOptionPane.showMessageDialog(this, "Extensi file yang disimpan adalah:" + a + b + c + d);

                JFileChooser fc = new JFileChooser();
                fc.setDialogTitle("Save File");
                fc.showSaveDialog(this);
                FileOutputStream fos = new FileOutputStream(fc.getSelectedFile().getAbsoluteFile().getAbsolutePath());
                fos.write(VigenereCipher.vigenereExtendedDecryptBytes(txtPassword.getText(), out));
                
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Gagal membuka file: " + e.getMessage());
                success = false;
            }
        }       
    }//GEN-LAST:event_btnExtractDataMouseClicked

    private void btnPSNRMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPSNRMouseClicked
        // TODO add your handling code here:
        JFileChooser fc = new JFileChooser();
        fc.setDialogTitle("Select File 1");
        fc.showOpenDialog(this);
        File file1 = fc.getSelectedFile();
        fc.setDialogTitle("Select File 2");
        fc.showOpenDialog(this);
        File file2 = fc.getSelectedFile();
        byte[] imageA = new byte[1];
        byte[] imageB= new byte[1];
        
        try
        {
            imageA = Files.readAllBytes(Paths.get(file1.getPath()));
            imageB = Files.readAllBytes(Paths.get(file2.getPath()));
             double psnr = stego.getPSNR(imageA, imageB);
            JOptionPane.showMessageDialog(this, "Nilai PSNR:" + Double.toString(psnr));
           
        } catch (Exception e)
        {   
            JOptionPane.showMessageDialog(this, "Gagal menghitung PSNR: " + e.getMessage() + " Cause:"+ e.getCause());
        }
        
    }//GEN-LAST:event_btnPSNRMouseClicked

    private void btnViewOriginalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnViewOriginalMouseClicked
        // TODO add your handling code here:
        JFrame frame = new JFrame();
        frame.getContentPane().setLayout(new FlowLayout());
        frame.getContentPane().add(new JLabel(new ImageIcon(image2)));
        frame.setTitle("Original Picture");
        frame.pack();
        frame.setVisible(true);
    }//GEN-LAST:event_btnViewOriginalMouseClicked

    private void btnViewSteganoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnViewSteganoMouseClicked
        // TODO add your handling code here:
        JFrame frame = new JFrame();
        frame.getContentPane().setLayout(new FlowLayout());
        frame.getContentPane().add(new JLabel(new ImageIcon(image1)));
        frame.setTitle("Stegano Picture");
        frame.pack();
        frame.setVisible(true);
    }//GEN-LAST:event_btnViewSteganoMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExtractData;
    private javax.swing.JButton btnLoadGambar;
    private javax.swing.JButton btnPSNR;
    private javax.swing.JButton btnPutData;
    private javax.swing.JButton btnViewOriginal;
    private javax.swing.JButton btnViewStegano;
    private javax.swing.JCheckBox checkGrayscale;
    private javax.swing.JComboBox cmbAlgoritma;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField txtKapasitas;
    private javax.swing.JTextField txtPassword;
    // End of variables declaration//GEN-END:variables
}
